Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = px.scatter(iris, x="sepal_width", y="sepal_length", color="species", marginal_y="violin",
           marginal_x="box", trendline="ols")
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-11-deadff2aa2ab>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m fig = px.scatter(iris, x="sepal_width", y="sepal_length", color="species", marginal_y="violin",
[0;32m----> 2[0;31m            marginal_x="box", trendline="ols")
[0m[1;32m      3[0m [0mfig[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/plotly/express/_chart_types.py[0m in [0;36mscatter[0;34m(data_frame, x, y, color, symbol, size, hover_name, hover_data, custom_data, text, facet_row, facet_col, facet_col_wrap, error_x, error_x_minus, error_y, error_y_minus, animation_frame, animation_group, category_orders, labels, color_discrete_sequence, color_discrete_map, color_continuous_scale, range_color, color_continuous_midpoint, symbol_sequence, symbol_map, opacity, size_max, marginal_x, marginal_y, trendline, trendline_color_override, log_x, log_y, range_x, range_y, render_mode, title, template, width, height)[0m
[1;32m     53[0m     [0mmark[0m [0;32min[0m [0;36m2[0m[0mD[0m [0mspace[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m     54[0m     """
[0;32m---> 55[0;31m     [0;32mreturn[0m [0mmake_figure[0m[0;34m([0m[0margs[0m[0;34m=[0m[0mlocals[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0mconstructor[0m[0;34m=[0m[0mgo[0m[0;34m.[0m[0mScatter[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     56[0m [0;34m[0m[0m
[1;32m     57[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/plotly/express/_core.py[0m in [0;36mmake_figure[0;34m(args, constructor, trace_patch, layout_patch)[0m
[1;32m   1528[0m [0;34m[0m[0m
[1;32m   1529[0m             patch, fit_results = make_trace_kwargs(
[0;32m-> 1530[0;31m                 [0margs[0m[0;34m,[0m [0mtrace_spec[0m[0;34m,[0m [0mgroup[0m[0;34m,[0m [0mmapping_labels[0m[0;34m.[0m[0mcopy[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0msizeref[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1531[0m             )
[1;32m   1532[0m             [0mtrace[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0mpatch[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/plotly/express/_core.py[0m in [0;36mmake_trace_kwargs[0;34m(args, trace_spec, trace_data, mapping_labels, sizeref)[0m
[1;32m    236[0m                     [0;32mand[0m [0mlen[0m[0;34m([0m[0mtrace_data[0m[0;34m)[0m [0;34m>[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m    237[0m                 ):
[0;32m--> 238[0;31m                     [0;32mimport[0m [0mstatsmodels[0m[0;34m.[0m[0mapi[0m [0;32mas[0m [0msm[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    239[0m [0;34m[0m[0m
[1;32m    240[0m                     [0;31m# sorting is bad but trace_specs with "trendline" have no other attrs[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'statsmodels'
ModuleNotFoundError: No module named 'statsmodels'

